import { CircleCheck, LifeBuoy } from 'lucide-react'
import { domainStoreUrl, siteUrl, supportEmail } from '../config'
import { Notice, PublicLayout } from '../components/PublicLayout'

function FeaturesPage() {
  const groups = [
    ['Mailbox and webmail', ['Professional addresses on your own domain', 'Roundcube Webmail access', 'IMAP and SMTP access for desktop and mobile clients', 'Mailbox quotas and one customer-owned domain per service', 'Account suspension without immediate deletion']],
    ['Routing and productivity', ['Aliases and domain aliases', 'Mailing list routing and custom delivery destinations', 'Email forwarding with optional local copy', 'Automatic replies and fetched accounts', 'Email filtering rules with ManageSieve', 'Full-text search for messages and attachments', 'Sender identities, signatures, folders, contacts and canned responses']],
    ['Security and delivery', ['DKIM signing', 'SPF and DMARC configuration guidance', 'TLS encrypted connections and client auto-configuration', 'Spam, malware and malicious-attachment protection', 'Per-account spam controls, anti-abuse limits and delivery monitoring']],
    ['Billing and lifecycle', ['Prepaid USD balance', 'Automatic service renewal', '30, 14, 7, 3 and 1-day reminders', 'Seven-day renewal grace period', 'Invoices and balance transaction history']],
    ['Operations', ['Automatic provisioning and retryable jobs', 'Domain DNS checklist with live verification', 'CSV export and support-assisted DNS review', 'Usage tracking and Enterprise storage overage records', 'Administrative audit logs and support assistance']],
  ]
  return <PublicLayout><section className="page-hero"><div className="container"><span className="eyebrow">Platform features</span><h1>Built for dependable business email operations.</h1><p>Mailbox access, delivery controls, automated billing and customer support are presented through one focused dashboard.</p></div></section><section className="section"><div className="container feature-groups">{groups.map(([title, items]) => <article key={title}><h2>{title}</h2><ul>{items.map((item) => <li key={item}><CircleCheck size={18} /> {item}</li>)}</ul></article>)}</div></section></PublicLayout>
}

function HowItWorksPage() {
  return <PublicLayout><section className="page-hero"><div className="container"><span className="eyebrow">Setup process</span><h1>From an existing domain to working mailboxes.</h1><p>The service does not register or include a domain name.</p></div></section><section className="section"><div className="container prose"><Notice tone="warning"><b>A registered domain is mandatory.</b> Purchase one from your preferred registrar or from <a href={domainStoreUrl}>domain.kmerhosting.com</a> before ordering.</Notice><h2>1. Create your account</h2><p>Register with a reachable contact email. This address receives billing, security and service notices.</p><h2>2. Add USD account credit</h2><p>There is no public payment gateway. Contact support and request the amount needed for your order. An administrator credits your account and the transaction appears in your billing history.</p><h2>3. Order email hosting</h2><p>Select a plan, enter the exact domain you already own and choose a term of 1, 3, 6, 12, 24 or 36 months. Each service covers one customer-owned domain.</p><h2>4. Configure DNS</h2><p>The dashboard displays MX, SPF, DKIM, DMARC and client auto-configuration records generated for your service. Publish them at your DNS provider. The dashboard checks them automatically and support can assist when needed.</p><h2>5. Create mailboxes</h2><p>After domain provisioning, create addresses such as info@yourcompany.com. Mailbox limits and storage quotas follow your selected plan. Open Webmail beside any active mailbox, or connect with IMAP and SMTP.</p><h2>6. Manage delivery</h2><p>Use aliases, forwarding, automatic replies and filtering rules for daily operations. Mailing list routing, domain aliases and advanced delivery destinations may require support-assisted configuration.</p><h2>7. Renew automatically</h2><p>Renewal is attempted from your USD balance. Reminders are sent beforehand. If credit is insufficient, the service enters a grace period before suspension.</p></div></section></PublicLayout>
}

function SupportPage() {
  return <PublicLayout><section className="page-hero"><div className="container"><span className="eyebrow">Support</span><h1>Help with credit, DNS and mailbox setup.</h1><p>Support is the only channel used to add USD credit to customer accounts.</p></div></section><section className="section"><div className="container support-card"><LifeBuoy size={36} /><h2>Contact KmerHosting Support</h2><p>Include your account email, domain and the amount of USD credit you need. Never send mailbox passwords or API secrets.</p><a className="button" href={`mailto:${supportEmail}?subject=Email%20Hosting%20Support`}>Email {supportEmail}</a></div></section></PublicLayout>
}

function LegalPage({ type }) {
  const privacy = type === 'privacy'
  return <PublicLayout><section className="page-hero small"><div className="container"><h1>{privacy ? 'Privacy Policy' : 'Terms of Service'}</h1><p>Last updated: August 4, 2026</p></div></section><section className="section"><article className="container prose legal">{privacy ? <>
    <h2>Scope</h2><p>This policy applies to the KmerHosting Email Hosting platform at {siteUrl}. The platform sells, provisions, manages and renews email hosting services for domains owned or controlled by customers.</p>
    <h2>Information we process</h2><p>We process account identity information, contact email addresses, company names, authentication and session records, customer domains, selected plans, service status, mailbox addresses, aliases, quotas, DNS verification status, USD account balances, wallet transactions, invoices, notifications, support requests and security audit records.</p>
    <h2>Mailbox and message data</h2><p>Email messages, attachments, contacts, folders and mailbox settings are stored and processed by the managed mail infrastructure to provide webmail, IMAP, SMTP, filtering, forwarding, automatic replies and backup functions. KmerHosting personnel do not access message content during ordinary operation. Exceptional access must be limited to security, restoration, abuse handling or legal requirements and should be logged where technically available.</p>
    <h2>Filtering and routing</h2><p>When enabled for a service, filtering rules, aliases, domain aliases, forwarding and mailing-list routing may inspect message headers and delivery metadata to route messages. These controls do not make KmerHosting the owner of customer message content.</p>
    <h2>Payments and account credit</h2><p>The platform does not provide a public payment gateway. Authorized KmerHosting personnel manually credit customer balances in USD. We retain the amount, reason, administrator, resulting balance and related audit information for accounting and fraud prevention.</p>
    <h2>How information is used</h2><p>Information is used to authenticate users, provision domains and mailboxes, enforce plan limits, process orders and renewals, issue invoices, send reminders, detect abuse, maintain backups, resolve support cases and protect the platform.</p>
    <h2>Service providers</h2><p>Cloud database and server-side function providers host application records and backend processing. The managed mail infrastructure stores and delivers mailbox data. A transactional email provider delivers account, billing and support notifications. Data is shared only as required to operate, secure and support the service.</p>
    <h2>Retention</h2><p>Account, invoice, transaction and audit data may be retained for legal, accounting, security and dispute-resolution purposes. Mailbox data is retained while a service is active and according to suspension, cancellation and backup retention rules communicated by KmerHosting. Suspension does not guarantee indefinite preservation.</p>
    <h2>Security</h2><p>Administrative credentials and notification credentials are kept on server-side systems and are not exposed to customers. Access is restricted through authentication, database policies, server secrets and audit records. No system can guarantee absolute security.</p>
    <h2>Your choices</h2><p>You may update account details, request correction of inaccurate information, disable automatic renewal, export mailbox content using standard mail protocols and request account closure, subject to legal retention requirements.</p>
    <h2>Contact</h2><p>Privacy questions may be sent to <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p>
  </> : <>
    <h2>Service description</h2><p>KmerHosting provides professional email hosting for domain names already owned or controlled by the customer. Domain registration, renewal and ownership are not included in any email hosting plan.</p>
    <h2>Customer domain and plan scope</h2><p>You must own or be authorized to manage the domain entered during checkout. Each purchased service covers one customer-owned domain. You are responsible for publishing the DNS records required for mail delivery. The mailbox count and storage quota are fixed by the selected plan; a service does not include additional domains or unlimited storage unless the plan expressly says so.</p>
    <h2>Plans and limits</h2><p>Mail Starter includes up to 10 mailboxes with 100 MB per mailbox. Mail Plus includes up to 30 mailboxes with 1 GB per mailbox. Mail Pro includes up to 200 mailboxes with 5 GB per mailbox. Mail Enterprise includes unlimited mailboxes with 10 GB per mailbox and additional storage billed at $0.005 per GB per month. All plans include webmail access, IMAP/SMTP client access, aliases, filtering, routing and security controls subject to service configuration, reasonable use and infrastructure constraints.</p>
    <h2>Webmail, filtering and routing</h2><p>Webmail provides message composition, folders, search, contacts, identities, signatures and attachments. Filtering rules, automatic replies, aliases, forwarding, domain aliases and mailing-list routing may be subject to the capabilities of the configured mail service and may require support-assisted setup. KmerHosting does not promise that every third-party webmail extension or advanced plugin will be enabled.</p>
    <h2>Billing</h2><p>Prices are denominated in USD. Orders and renewals are deducted from prepaid account credit. Three- and six-month terms have no discount. Twelve-month terms receive 10% off, twenty-four-month terms receive 20% off and thirty-six-month terms receive 30% off. Credit is added manually by authorized KmerHosting personnel and is not cash unless required by law.</p>
    <h2>Renewals and suspension</h2><p>Services with automatic renewal enabled are renewed from available account credit. The platform sends reminders before renewal. Insufficient credit may place the service in a grace period followed by suspension. Suspended mailboxes cannot reliably send or receive messages. Continued non-payment may lead to cancellation and deletion under the applicable retention policy.</p>
    <h2>Acceptable use and sending limits</h2><p>You must not use the service for unsolicited bulk email, phishing, malware, credential theft, illegal content, impersonation, abuse, harassment or attempts to damage third-party systems. Sending quotas, anti-spam controls, attachment restrictions and rate limits may apply. KmerHosting may suspend compromised or abusive accounts immediately to protect delivery reputation and other customers.</p>
    <h2>Backups</h2><p>Automatic backups are part of the service architecture, but backups are not an archival guarantee. Customers should maintain independent copies of business-critical messages. Restoration may depend on backup age, integrity and retention limits.</p>
    <h2>Availability and delivery</h2><p>Email delivery depends on DNS, sender reputation, recipient policies, internet routing and third-party systems. KmerHosting does not guarantee that every message will be accepted or placed in a recipient inbox.</p>
    <h2>Contact</h2><p>Service questions and credit requests may be sent to <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p>
  </>}</article></section></PublicLayout>
}

export { FeaturesPage, HowItWorksPage, SupportPage, LegalPage }
