import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const MAILU_API_BASE = (Deno.env.get("MAILU_API_BASE") ?? "https://mail.kmerhosting.com/api/v1").replace(/\/$/, "");
const MAILU_API_TOKEN = Deno.env.get("MAILU_API_TOKEN") ?? "";
const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
function errorMessage(error: unknown) { return error instanceof Error ? error.message : String(error); }
async function mailuToken() {
  if (MAILU_API_TOKEN) return MAILU_API_TOKEN;
  const { data, error } = await admin.rpc("eh_get_mailu_api_token");
  if (error || typeof data !== "string" || !data) throw new Error("Mailu API token is not configured on the server.");
  return data;
}
async function mailu(path: string, init: RequestInit = {}) {
  const token = await mailuToken();
  const result = await fetch(`${MAILU_API_BASE}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init.headers ?? {}) } });
  const text = await result.text(); let payload: unknown = null; try { payload = text ? JSON.parse(text) : null; } catch { payload = text; }
  if (!result.ok) { const message = typeof payload === "object" && payload && "message" in payload ? String((payload as { message: unknown }).message) : `Mailu returned HTTP ${result.status}`; const error = new Error(message) as Error & { status?: number }; error.status = result.status; throw error; }
  return payload;
}
async function configValue(key: string, fallback: string) { const { data } = await admin.from("eh_config").select("value").eq("key", key).maybeSingle(); return String(data?.value || fallback); }
async function mailtrapToken() { const { data, error } = await admin.rpc("eh_get_mailtrap_api_token"); if (error || typeof data !== "string" || !data || data === "not-configured") throw new Error("Mailtrap is not configured on the server."); return data; }
function emailHtml(subject: string, payload: Record<string, unknown>) { const rows = Object.entries(payload).filter(([key, value]) => key !== "csv" && key !== "replyTo" && value !== null && value !== undefined && value !== "").map(([key, value]) => `<tr><td style="padding:8px;color:#666">${key}</td><td style="padding:8px;font-weight:600">${String(value)}</td></tr>`).join(""); return `<!doctype html><html lang="en"><body style="font-family:Arial,sans-serif;background:#f7f7f7;padding:24px"><main style="max-width:620px;margin:auto;background:#fff;padding:32px;border-top:4px solid #0e8420"><h1>${subject}</h1><p>This is an automated KmerHosting Email Hosting notification.</p>${rows ? `<table style="width:100%;border-collapse:collapse;background:#fafafa">${rows}</table>` : ""}<p style="color:#666">Support: support@kmerhosting.com</p></main></body></html>`; }
function base64(value: string) { const bytes = new TextEncoder().encode(value); let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }
async function processEmailOutbox(limit = 20) { const { data: rows, error } = await admin.from("eh_email_outbox").select("*").in("status", ["pending", "failed"]).lte("next_attempt_at", new Date().toISOString()).order("created_at").limit(limit); if (error) throw error; let sent = 0; for (const row of rows ?? []) { const attempts = Number(row.attempts) + 1; await admin.from("eh_email_outbox").update({ status: "processing", attempts }).eq("id", row.id); try { const payload = (row.payload || {}) as Record<string, unknown>; const attachments = typeof payload.csv === "string" ? [{ content: base64(payload.csv), filename: String(payload.attachmentFilename || "dns-records.csv"), type: "text/csv", disposition: "attachment" }] : undefined; const replyTo = typeof payload.replyTo === "string" ? { email: payload.replyTo } : undefined; const result = await fetch(await configValue("mailtrap_api_url", "https://send.api.mailtrap.io/api/send"), { method: "POST", headers: { Authorization: `Bearer ${await mailtrapToken()}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: { email: await configValue("mailtrap_from_email", "support@kmerhosting.com"), name: await configValue("mailtrap_from_name", "KmerHosting") }, to: [{ email: row.recipient }], reply_to: replyTo, attachments, subject: `${await configValue("email_subject_prefix", "[KmerHosting]")} ${row.subject}`, html: emailHtml(row.subject, payload), category: `email-hosting-${row.template_key}` }) }); if (!result.ok) throw new Error(`Mailtrap returned HTTP ${result.status}`); await admin.from("eh_email_outbox").update({ status: "sent", sent_at: new Date().toISOString(), last_error: null }).eq("id", row.id); sent += 1; } catch (error) { await admin.from("eh_email_outbox").update({ status: "failed", last_error: errorMessage(error).slice(0, 1000), next_attempt_at: new Date(Date.now() + Math.min(1440, 2 ** Math.min(attempts, 10)) * 60_000).toISOString() }).eq("id", row.id); } } return sent; }
async function setDomainUsersEnabled(domain: string, enabled: boolean) { const payload = await mailu(`/domain/${encodeURIComponent(domain)}/users`); const users = Array.isArray(payload) ? payload : []; const emails: string[] = []; for (const item of users) { const email = String((item as Record<string, unknown>).email ?? ""); if (!email) continue; emails.push(email); await mailu(`/user/${encodeURIComponent(email)}`, { method: "PATCH", body: JSON.stringify({ enabled }) }); } if (emails.length) await admin.from("eh_mailboxes").update({ enabled }).in("email", emails); }
function dnsRows(serviceId: string, domain: string, details: Record<string, unknown>) { const rows: Array<Record<string, unknown>> = []; const add = (recordType: string, hostname: string, value: unknown, priority: number | null = null) => { if (value == null || value === "") return; if (Array.isArray(value)) return value.forEach((item) => add(recordType, hostname, item, priority)); String(value).split("\n").map((item) => item.trim()).filter(Boolean).forEach((item) => rows.push({ service_id: serviceId, record_type: recordType, hostname, value: item, priority, status: "pending" })); }; add("MX", domain, details.dns_mx, 10); add("TXT", domain, details.dns_spf); add("TXT", domain, details.dns_dkim); add("TXT", domain, details.dns_dmarc); add("TXT", domain, details.dns_dmarc_report); add("TLSA", `_25._tcp.${domain}`, details.dns_tlsa); add("AUTOCONFIG", domain, details.dns_autoconfig); return rows; }
async function provision(service: Record<string, unknown>) { const domain = String(service.domain_name); try { await mailu("/domain", { method: "POST", body: JSON.stringify({ name: domain, comment: `KmerHosting Email service ${service.id}`, max_users: service.mailbox_limit ?? -1, max_aliases: -1, max_quota_bytes: Number(service.storage_bytes_per_mailbox), signup_enabled: false }) }); } catch (error) { if ((error as Error & { status?: number }).status !== 409) throw error; } try { await mailu(`/domain/${encodeURIComponent(domain)}/dkim`, { method: "POST", body: "{}" }); } catch { } const details = await mailu(`/domain/${encodeURIComponent(domain)}`) as Record<string, unknown>; const rows = dnsRows(String(service.id), domain, details); await admin.from("eh_dns_records").delete().eq("service_id", service.id); if (rows.length) await admin.from("eh_dns_records").insert(rows); await admin.from("eh_services").update({ status: "active", mailu_domain_created: true, last_provisioned_at: new Date().toISOString() }).eq("id", service.id); }
async function processJobs(limit = 50) { const { data: jobs, error } = await admin.from("eh_provisioning_jobs").select("*").in("status", ["pending", "failed"]).lte("next_attempt_at", new Date().toISOString()).order("created_at").limit(limit); if (error) throw error; let completed = 0; for (const job of jobs ?? []) { const attempts = Number(job.attempts) + 1; await admin.from("eh_provisioning_jobs").update({ status: "processing", attempts, locked_at: new Date().toISOString() }).eq("id", job.id); try { const { data: service, error: serviceError } = await admin.from("eh_services").select("*").eq("id", job.service_id).single(); if (serviceError || !service) throw new Error("Service not found."); if (job.job_type === "create_domain") await provision(service); else if (job.job_type === "suspend_domain") await setDomainUsersEnabled(service.domain_name, false); else if (job.job_type === "resume_domain") await setDomainUsersEnabled(service.domain_name, true); else if (job.job_type === "sync_dns") { const details = await mailu(`/domain/${encodeURIComponent(service.domain_name)}`) as Record<string, unknown>; const rows = dnsRows(service.id, service.domain_name, details); await admin.from("eh_dns_records").delete().eq("service_id", service.id); if (rows.length) await admin.from("eh_dns_records").insert(rows); } else throw new Error(`Unsupported job type: ${job.job_type}`); await admin.from("eh_provisioning_jobs").update({ status: "completed", completed_at: new Date().toISOString(), last_error: null }).eq("id", job.id); completed += 1; } catch (error) { const terminal = attempts >= Number(job.max_attempts); await admin.from("eh_provisioning_jobs").update({ status: terminal ? "cancelled" : "failed", last_error: errorMessage(error), next_attempt_at: new Date(Date.now() + Math.min(3600, 30 * 2 ** attempts) * 1000).toISOString() }).eq("id", job.id); } } return completed; }
Deno.serve(async (req: Request) => { if (req.method !== "POST") return new Response("Method not allowed", { status: 405 }); const { data: expectedSecret, error: secretError } = await admin.rpc("eh_get_automation_secret"); if (secretError || !expectedSecret || req.headers.get("x-automation-secret") !== expectedSecret) return new Response("Forbidden", { status: 403 }); const { data: run } = await admin.from("eh_cron_runs").insert({ job_name: "eh_mailu_automation" }).select("id").single(); try { const [processed, emails] = await Promise.all([processJobs(), processEmailOutbox()]); if (run?.id) await admin.from("eh_cron_runs").update({ status: "completed", completed_at: new Date().toISOString(), processed_count: processed + emails }).eq("id", run.id); return new Response(JSON.stringify({ ok: true, processed, emails }), { headers: { "Content-Type": "application/json" } }); } catch (error) { if (run?.id) await admin.from("eh_cron_runs").update({ status: "failed", completed_at: new Date().toISOString(), error_message: errorMessage(error) }).eq("id", run.id); return new Response(JSON.stringify({ ok: false, error: errorMessage(error) }), { status: 500, headers: { "Content-Type": "application/json" } }); } });
