alter table public.eh_profiles enable row level security;
alter table public.eh_wallets enable row level security;
alter table public.eh_wallet_transactions enable row level security;
alter table public.eh_plans enable row level security;
alter table public.eh_billing_terms enable row level security;
alter table public.eh_mailu_clusters enable row level security;
alter table public.eh_orders enable row level security;
alter table public.eh_services enable row level security;
alter table public.eh_mailboxes enable row level security;
alter table public.eh_aliases enable row level security;
alter table public.eh_autoresponders enable row level security;
alter table public.eh_dns_records enable row level security;
alter table public.eh_invoices enable row level security;
alter table public.eh_notifications enable row level security;
alter table public.eh_email_outbox enable row level security;
alter table public.eh_provisioning_jobs enable row level security;
alter table public.eh_storage_usage_snapshots enable row level security;
alter table public.eh_usage_charges enable row level security;
alter table public.eh_audit_logs enable row level security;
alter table public.eh_cron_runs enable row level security;

DO $$ DECLARE r record; BEGIN FOR r IN select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename like 'eh_%' LOOP execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename); END LOOP; END $$;
create policy eh_profiles_select on public.eh_profiles for select using(id=auth.uid() or public.eh_is_admin());
create policy eh_wallets_select on public.eh_wallets for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_wallet_transactions_select on public.eh_wallet_transactions for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_plans_public_select on public.eh_plans for select using(active=true or public.eh_is_admin());
create policy eh_billing_terms_public_select on public.eh_billing_terms for select using(active=true or public.eh_is_admin());
create policy eh_orders_select on public.eh_orders for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_services_select on public.eh_services for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_services_update on public.eh_services for update using(user_id=auth.uid() or public.eh_is_admin()) with check(user_id=auth.uid() or public.eh_is_admin());
create policy eh_mailboxes_select on public.eh_mailboxes for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_aliases_select on public.eh_aliases for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_autoresponders_select on public.eh_autoresponders for select using(exists(select 1 from public.eh_mailboxes m where m.id=mailbox_id and(m.user_id=auth.uid() or public.eh_is_admin())));
create policy eh_dns_records_select on public.eh_dns_records for select using(exists(select 1 from public.eh_services s where s.id=service_id and(s.user_id=auth.uid() or public.eh_is_admin())));
create policy eh_invoices_select on public.eh_invoices for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_notifications_select on public.eh_notifications for select using(user_id=auth.uid() or public.eh_is_admin());
create policy eh_notifications_update on public.eh_notifications for update using(user_id=auth.uid() or public.eh_is_admin()) with check(user_id=auth.uid() or public.eh_is_admin());
create policy eh_storage_usage_select on public.eh_storage_usage_snapshots for select using(exists(select 1 from public.eh_services s where s.id=service_id and(s.user_id=auth.uid() or public.eh_is_admin())));
create policy eh_usage_charges_select on public.eh_usage_charges for select using(exists(select 1 from public.eh_services s where s.id=service_id and(s.user_id=auth.uid() or public.eh_is_admin())));
create policy eh_admin_clusters on public.eh_mailu_clusters for all using(public.eh_is_admin()) with check(public.eh_is_admin());
create policy eh_admin_jobs on public.eh_provisioning_jobs for all using(public.eh_is_admin()) with check(public.eh_is_admin());
create policy eh_admin_audit on public.eh_audit_logs for select using(public.eh_is_admin());
create policy eh_admin_cron on public.eh_cron_runs for select using(public.eh_is_admin());

revoke all on public.eh_profiles,public.eh_wallets,public.eh_wallet_transactions,public.eh_orders,public.eh_services,public.eh_mailboxes,public.eh_aliases,public.eh_autoresponders,public.eh_dns_records,public.eh_invoices,public.eh_notifications,public.eh_email_outbox,public.eh_provisioning_jobs,public.eh_storage_usage_snapshots,public.eh_usage_charges,public.eh_audit_logs,public.eh_cron_runs,public.eh_mailu_clusters from anon,authenticated;
grant select on public.eh_plans,public.eh_billing_terms to anon,authenticated;
grant select on public.eh_profiles,public.eh_wallets,public.eh_wallet_transactions,public.eh_orders,public.eh_services,public.eh_mailboxes,public.eh_aliases,public.eh_autoresponders,public.eh_dns_records,public.eh_invoices,public.eh_notifications,public.eh_storage_usage_snapshots,public.eh_usage_charges to authenticated;
grant update(read_at) on public.eh_notifications to authenticated;
grant update(auto_renew) on public.eh_services to authenticated;
grant execute on function public.eh_is_admin() to authenticated;
grant execute on function public.eh_purchase_service(text,integer,text) to authenticated;
grant execute on function public.eh_admin_credit_wallet(text,numeric,text,text) to authenticated;
grant execute on function public.eh_update_profile(text,text) to authenticated;
revoke execute on function public.eh_queue_renewal_reminders() from public,anon,authenticated;
revoke execute on function public.eh_process_due_renewals() from public,anon,authenticated;
revoke execute on function public.eh_suspend_expired_services() from public,anon,authenticated;

comment on table public.eh_profiles is 'Email Hosting customer profiles. auth.users remains the authentication source.';
comment on table public.eh_wallets is 'Prepaid USD balance. Customers cannot mutate balances directly.';
comment on table public.eh_services is 'Email hosting services for customer-owned domains. No domain registration is included.';
comment on table public.eh_provisioning_jobs is 'Idempotent Mailu lifecycle queue processed by Edge Functions.';
