create index if not exists eh_aliases_service_id_idx on public.eh_aliases(service_id);
create index if not exists eh_aliases_user_id_idx on public.eh_aliases(user_id);
create index if not exists eh_audit_logs_actor_idx on public.eh_audit_logs(actor_user_id, created_at desc);
create index if not exists eh_audit_logs_target_idx on public.eh_audit_logs(target_user_id, created_at desc);
create index if not exists eh_email_outbox_user_idx on public.eh_email_outbox(user_id, created_at desc);
create index if not exists eh_invoices_service_idx on public.eh_invoices(service_id);
create index if not exists eh_invoices_order_idx on public.eh_invoices(order_id);
create index if not exists eh_mailboxes_user_idx on public.eh_mailboxes(user_id);
create index if not exists eh_orders_plan_idx on public.eh_orders(plan_id);
create index if not exists eh_orders_term_idx on public.eh_orders(term_months);
create index if not exists eh_orders_wallet_transaction_idx on public.eh_orders(wallet_transaction_id);
create index if not exists eh_orders_service_idx on public.eh_orders(service_id);
create index if not exists eh_provisioning_jobs_service_idx on public.eh_provisioning_jobs(service_id);
create index if not exists eh_provisioning_jobs_mailbox_idx on public.eh_provisioning_jobs(mailbox_id);
create index if not exists eh_services_order_idx on public.eh_services(order_id);
create index if not exists eh_services_plan_idx on public.eh_services(plan_id);
create index if not exists eh_services_term_idx on public.eh_services(term_months);
create index if not exists eh_services_cluster_idx on public.eh_services(cluster_id);
create index if not exists eh_storage_usage_mailbox_idx on public.eh_storage_usage_snapshots(mailbox_id);
create index if not exists eh_usage_charges_invoice_idx on public.eh_usage_charges(invoice_id);
create index if not exists eh_wallet_transactions_created_by_idx on public.eh_wallet_transactions(created_by);

drop policy if exists eh_profiles_select on public.eh_profiles;
create policy eh_profiles_select on public.eh_profiles for select using (id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_wallets_select on public.eh_wallets;
create policy eh_wallets_select on public.eh_wallets for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_wallet_transactions_select on public.eh_wallet_transactions;
create policy eh_wallet_transactions_select on public.eh_wallet_transactions for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_plans_public_select on public.eh_plans;
create policy eh_plans_public_select on public.eh_plans for select using (active = true or (select public.eh_is_admin()));
drop policy if exists eh_billing_terms_public_select on public.eh_billing_terms;
create policy eh_billing_terms_public_select on public.eh_billing_terms for select using (active = true or (select public.eh_is_admin()));
drop policy if exists eh_orders_select on public.eh_orders;
create policy eh_orders_select on public.eh_orders for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_services_select on public.eh_services;
create policy eh_services_select on public.eh_services for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_services_update on public.eh_services;
create policy eh_services_update on public.eh_services for update using (user_id = (select auth.uid()) or (select public.eh_is_admin())) with check (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_mailboxes_select on public.eh_mailboxes;
create policy eh_mailboxes_select on public.eh_mailboxes for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_aliases_select on public.eh_aliases;
create policy eh_aliases_select on public.eh_aliases for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_autoresponders_select on public.eh_autoresponders;
create policy eh_autoresponders_select on public.eh_autoresponders for select using (exists(select 1 from public.eh_mailboxes m where m.id = mailbox_id and (m.user_id = (select auth.uid()) or (select public.eh_is_admin()))));
drop policy if exists eh_dns_records_select on public.eh_dns_records;
create policy eh_dns_records_select on public.eh_dns_records for select using (exists(select 1 from public.eh_services s where s.id = service_id and (s.user_id = (select auth.uid()) or (select public.eh_is_admin()))));
drop policy if exists eh_invoices_select on public.eh_invoices;
create policy eh_invoices_select on public.eh_invoices for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_notifications_select on public.eh_notifications;
create policy eh_notifications_select on public.eh_notifications for select using (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_notifications_update on public.eh_notifications;
create policy eh_notifications_update on public.eh_notifications for update using (user_id = (select auth.uid()) or (select public.eh_is_admin())) with check (user_id = (select auth.uid()) or (select public.eh_is_admin()));
drop policy if exists eh_storage_usage_select on public.eh_storage_usage_snapshots;
create policy eh_storage_usage_select on public.eh_storage_usage_snapshots for select using (exists(select 1 from public.eh_services s where s.id = service_id and (s.user_id = (select auth.uid()) or (select public.eh_is_admin()))));
drop policy if exists eh_usage_charges_select on public.eh_usage_charges;
create policy eh_usage_charges_select on public.eh_usage_charges for select using (exists(select 1 from public.eh_services s where s.id = service_id and (s.user_id = (select auth.uid()) or (select public.eh_is_admin()))));
drop policy if exists eh_config_admin_select on public.eh_config;
create policy eh_config_admin_select on public.eh_config for select using ((select public.eh_is_admin()));
drop policy if exists eh_email_outbox_admin_select on public.eh_email_outbox;
create policy eh_email_outbox_admin_select on public.eh_email_outbox for select using ((select public.eh_is_admin()));
drop policy if exists eh_admin_clusters on public.eh_mailu_clusters;
create policy eh_admin_clusters on public.eh_mailu_clusters for all using ((select public.eh_is_admin())) with check ((select public.eh_is_admin()));
drop policy if exists eh_admin_jobs on public.eh_provisioning_jobs;
create policy eh_admin_jobs on public.eh_provisioning_jobs for all using ((select public.eh_is_admin())) with check ((select public.eh_is_admin()));
drop policy if exists eh_admin_audit on public.eh_audit_logs;
create policy eh_admin_audit on public.eh_audit_logs for select using ((select public.eh_is_admin()));
drop policy if exists eh_admin_cron on public.eh_cron_runs;
create policy eh_admin_cron on public.eh_cron_runs for select using ((select public.eh_is_admin()));
